apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-frontend
  template:
    metadata:
      labels:
        app: crm-frontend
    spec:
      containers:
      - name: frontend
        image: resources-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000